require:
  - rubocop-factory_bot
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

Layout/LineLength:
  Max: 120

Rspec/ContextWording:
  Enabled: false

Rspec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false
