services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=risk_development
    volumes:
      - ./postgres:/var/lib/postgresql/data
networks:
  default:
    external: true
    name: risk
